@startuml
skinparam shadowing false
skinparam monochrome true

' hide the spot
hide circle

' avoid problems with angled crows feet
skinparam linetype ortho

object "Bundle" as bundle {
  TrustDomain : string
--
  Data : bytes
}

object "FederatedRegistrationEntry" as fre {
  TrustDomain: string
  EntryID: string
}

object "RegisteredEntry" as re {
  EntryID : string
--
  SpiffeID : string
  ParentID : string
  TTL : int32
  Admin : bool
  Downstream : bool
  Expiry : int64
  RevisionNumber : int64
}

object "JoinToken" as jt {
  Token : string
--
  Expiry : int64
}


object "Selector" as selector {
RegisteredEntryId : string
--
Type : string
Value : string
}

object "DNSName" as dnsname {
RegisteredEntryId : string
--
Value : string
}

object "AttestedNode" as attestednode {
SpiffeID : string
--
DataType : string
SerialNumber : string
ExpiresAt : time
NewSerialNumber : string
NewExpiresAt : time
}

object "NodeSelector" as nodeselector {
SpiffeID : string
--
Type : string
Value : string
}

bundle --|{ fre
re --|{ fre
re --|{ selector
re --|{ dnsname
attestednode --|{ nodeselector
@enduml
